--1-Database exploration
-- explore all objects in the database 
select *from INFORMATION_SCHEMA.TABLES

-- explore all objects in the database 
select *from INFORMATION_SCHEMA.COLUMNS

--2-Dimensions Exploration
select distinct country from gold.dim_customers
select distinct category, subcategory , product_name from gold.dim_products

--3-Date Exploration
-- find the date of the first and last order 
select min(order_date) first_order_date, max(order_date ) last_order_date,datediff(year,min(order_date),max(order_date)) as Order_range_Years from gold.fact_sales
-- find the youngest and the oldest customer
select min(birthdate) the_oldest , datediff(year,min(birthdate),getdate()) as oldest_age , max(birthdate) the_youngest,datediff(year,max(birthdate),getdate()) as youngest_age from gold.dim_customers

--4-Measures Exploration
--Find the total sales 
select sum(sales_amount) as total_sales from gold.fact_sales
--Find how many items are sold 
select sum(quantity) as total_quantity from gold.fact_sales
--Find the average selling price 
select avg(price) as avr_price from gold.fact_sales
--Find the total number of Orders
select count(distinct order_number) as total_orders from gold.fact_sales
--Find the total number of Products
select count(distinct product_key) as total_product from gold.dim_products
--Find the total number of Customers
select count(distinct customer_key) as total_customers from gold.dim_customers
--Find the total number of Customers that has placed an order
select count(distinct customer_key) as total_customers from gold.fact_sales

--Create a table that shows all the key metrics you got above 
select 'Total_sales' as Measure_name ,sum(sales_amount) as Measure_value from gold.fact_sales
union all 
select 'Total_Quantity' as Measure_name ,sum(quantity) as Measure_value from gold.fact_sales
union all 
select 'Average_price' as Measure_name ,avg(price) as Measure_value from gold.fact_sales
union all 
select 'Total Num.Orders' as Measure_name ,count(distinct order_number)as Measure_value from gold.fact_sales
union all 
select 'Total Num.Products' as Measure_name ,count(distinct product_key) as Measure_value from gold.fact_sales
union all 
select 'Total Num.Customers' as Measure_name ,count(distinct customer_key) as Measure_value from gold.fact_sales

--5-Magnitude Analysis
--Find total customers by Country 
Select Country , COUNT(customer_key) as Total_customers from gold.dim_customers group by country

--Find total customers by gender 
Select gender , COUNT(customer_key) as Total_customers from gold.dim_customers group by gender

--Find total Products by Category
Select category , COUNT(distinct product_key) as Total_Products from gold.dim_products group by category order by Total_Products desc

--What are the average costs in each category?
Select category , avg(cost) as AVR_cost from gold.dim_products group by category 

--What is the Total revenue generated for each category? 
select p.category, sum ( f.sales_amount) as total_revenue
from gold.fact_sales f 
left join gold.dim_products p
on p.product_key = f. product_key
group by p.category  order  by total_revenue asc 

--Find total revenue generated by each customer
select 
c.first_name,c.last_name, sum ( f.sales_amount) as total_revenue
from gold.fact_sales f 
left join gold.dim_customers c
on c.customer_key = f. customer_key
group by c.first_name,c.last_name
order  by total_revenue desc 

-- What is the distribution of sold items across countries ? 
select c.country, sum ( f.quantity) as total_sold_amount
from gold.fact_sales f 
left join gold.dim_customers c
on c.customer_key = f. customer_key
group by country
order  by total_sold_amount desc 

--6-Ranking Analysis
-- Top 5 products by revenue
select top 5 
p.product_name , 
sum (f.sales_amount) total_revenue
from gold.fact_sales f
left join gold.dim_products p
on p.product_key = f.product_key
group by p.product_name
order by total_revenue Desc

--worst 5 performing products in terms of sales 
select top 5 
p.product_name , 
sum (f.sales_amount) total_revenue
from gold.fact_sales f
left join gold.dim_products p
on p.product_key = f.product_key
group by p.product_name
order by total_revenue 

-- Top 5 products by revenue using the Window Function 
select * from (
select 
    p.product_name , 
    sum (f.sales_amount) as total_revenue,
    ROW_NUMBER () OVER (order by sum(f.sales_amount) DESC ) as rank_products
   from gold.fact_sales f
    left join gold.dim_products p
on p.product_key = f.product_key
group by p.product_name ) as tbl
where rank_products <=5 

--Top 10 Customers generating revenue
select top 10
c.first_name,c.last_name, sum ( f.sales_amount) as total_revenue
from gold.fact_sales f 
left join gold.dim_customers c
on c.customer_key = f. customer_key
group by c.first_name,c.last_name
order  by total_revenue desc 

--the lowest 3 customers placing orders
select top 3  c.customer_key , c.first_name , c.last_name,
count (  order_number) as total_orders 
from gold.fact_sales f 
left join gold.dim_customers c 
on c.customer_key = f.customer_key 
group by c.customer_key , c.first_name , c.last_name 
order by total_orders  asc 

--Top revenue customers contributing most of total sales
select  top 5 
c.customer_key ,c.first_name , c.last_name ,SUM(f.sales_amount) as Total_revenue from gold.fact_sales f 
inner join gold.dim_customers c
ON c.customer_key = f.customer_key
group by c.customer_key ,c.first_name , c.last_name 
order by Total_revenue desc

--Who are the top 10 customers generating the highest revenue& calculate average order value per customer
select  top 10
	c.customer_key ,c.first_name , c.last_name ,SUM(f.sales_amount) as Total_revenue , COUNT(distinct f.order_number ) as Orders , SUM(f.sales_amount) /COUNT(distinct f.order_number ) as AVG_Order_value
	from gold.fact_sales f 
inner join gold.dim_customers c
ON c.customer_key = f.customer_key
group by c.customer_key ,c.first_name , c.last_name 
order by Total_revenue desc
